# Generated by Django 6.0.3 on 2026-03-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_rate',
            field=models.FloatField(choices=[(0, '0%'), (13.5, '13.5%'), (25.5, '25.5%')], default=25.5),
        ),
    ]
