# Generated by Django 6.0.3 on 2026-03-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_subtotal_invoice_vat_amount_invoice_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='week_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
