# Generated by Django 6.0.3 on 2026-03-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_week_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='week_number',
        ),
        migrations.AddField(
            model_name='invoice',
            name='hourly_rate',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('hourly', 'Hourly invoice'), ('weekly', 'Weekly invoice'), ('fixed', 'Fixed amount invoice')], default='hourly', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='weeks_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='work_hours',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
